const AsideData = [
  {
    level: "1",
    category: "1",
    room: "Stacks",
    spaces: "1.01",
    title: "Darylyne Provost",
  },
  {
    level: "1",
    category: "1",
    room: "Stacks",
    spaces: "1.02",
    title: "Mike McGuire",
  },
  {
    level: "1",
    category: "1",
    room: "Stacks",
    spaces: "1.03",
    title: "Matt LeVan",
  },
  {
    level: "1",
    category: "1",
    spaces: "1.04",
    room: "MFLM",
    title: "Mike Jandreau",
  },
  {
    level: "1",
    category: "4",
    room: "MFLM",
    spaces: "1.05",
    title: "Eileen Richards",
  },
  {
    level: "1",
    category: "1",
    room: "MFLM",
    spaces: "1.06",
    title: "Ground Level Stacks",
  },
  {
    level: "1",
    category: "1",
    room: "MFLM",
    spaces: "1.07",
    title: "Mike McGuire",
  },
  {
    level: "2",
    category: "2",
    room: "NB",
    spaces: "2.01",
    title: "Special Collections Processing",
  },
  {
    level: "2",
    category: "2",
    room: "134",
    spaces: "2.02",
    title: "Ana Noriega",
  },
  {
    level: "2",
    category: "2",
    room: "MFLM",
    spaces: "2.03",
    title: "Katie Donahue",
  },
  {
    level: "2",
    category: "3",
    room: "134",
    spaces: "2.04",
    title: "Room 004",
  },
  {
    level: "2",
    category: "3",
    room: "MFLM",
    spaces: "2.05",
    title: "Bess Stokes",
  },
  {
    level: "2",
    category: "1",
    room: "Mule Works",
    spaces: "2.06",
    title: "Study Rooms 20A-D",
  },
  {
    level: "2",
    category: "4",
    room: "Hall",
    spaces: "2.07",
    title: "Microfilm",
  },
  {
    level: "3",
    category: "2",
    room: "SC",
    spaces: "3.01",
    title: "Hall Study Area",
  },
  {
    level: "3",
    category: "3",
    room: "SCP",
    spaces: "3.02",
    title: "Mike McGuire",
  },
  {
    level: "3",
    category: "4",
    room: "020A-D",
    spaces: "3.03",
    title: "Seminar Room",
  },

  {
    level: "3",
    category: "4",
    room: "Hall",
    spaces: "3.04",
    title: "Lauren Yoshizawa",
  },

  {
    level: "3",
    category: "4",
    room: "SC",
    spaces: "3.05",
    title: "Celeste Cessaro",
  },

  {
    level: "3",
    category: "3",
    room: "SCP",
    spaces: "3.06",
    title: "David Casalaspi",
  },

  {
    level: "3",
    category: "4",
    room: "Stacks",
    spaces: "3.07",
    title: "Lyn Brown & Mark Tappan",
  },

  {
    level: "4",
    category: "3",
    room: "Stacks",
    spaces: "4.01",
    title: "Adam Howard",
  },
  {
    level: "4",
    category: "3",
    room: "134",
    spaces: "4.02",
    title: "Darylyne Provost",
  },
  {
    level: "4",
    category: "4",
    room: "Hall",
    spaces: "4.03",
    title: "Ellen Freeman",
  },
  {
    level: "4",
    category: "4",
    room: "SC",
    spaces: "4.04",
    title: "Adam Howard",
  },
  {
    level: "4",
    category: "4",
    room: "SCP",
    spaces: "4.05",
    title: "Robinson Room",
  },
  {
    level: "4",
    category: "4",
    room: "SCP",
    spaces: "4.06",
    title: "Adam Howard",
  },
  {
    level: "4",
    category: "4",
    room: "SC",
    spaces: "4.07",
    title: "ROOOOOM 3",
  },

  {
    level: "5",
    category: "2",
    room: "Stacks",
    spaces: "5.01",
    title: "Rachel Gammon",
  },
  {
    level: "5",
    category: "3",
    room: "Stacks",
    spaces: "5.02",
    title: "Service Desk",
  },
  {
    level: "5",
    category: "2",
    room: "Stacks",
    spaces: "5.03",
    title: "Healy Room",
  },
  {
    level: "5",
    category: "2",
    room: "Halls",
    spaces: "5.04",
    title: "Tim Stonsifer",
  },
  {
    level: "5",
    category: "2",
    room: "Stacks",
    spaces: "5.05",
    title: "Lareese Hall",
  },
  {
    level: "5",
    category: "2",
    room: "SCP",
    spaces: "5.06",
    title: "Fit Lab",
  },
  {
    level: "5",
    category: "2",
    room: "134",
    spaces: "5.07",
    title: "Wormser Room",
  },

  {
    level: "6",
    category: "2",
    room: "134",
    spaces: "6.01",
    title: "Chapman Room",
  },
  {
    level: "6",
    category: "2",
    room: "Hall",
    spaces: "6.02",
    title: "Special Collections",
  },
  {
    level: "6",
    category: "2",
    room: "134",
    spaces: "6.03",
    title: "New Books",
  },
  {
    level: "6",
    category: "2",
    room: "134",
    spaces: "6.04",
    title: "Colby Authors",
  },
  {
    level: "6",
    category: "2",
    room: "134",
    spaces: "6.05",
    title: "April Paul",
  },
  {
    level: "6",
    category: "2",
    room: "Hall",
    spaces: "6.06",
    title: "Darylyne Provost",
  },
  {
    level: "6",
    category: "2",
    room: "SCP",
    spaces: "6.07",
    title: "Reference Books",
  },

  {
    level: "7",
    category: "3",
    room: "Hall",
    spaces: "7.01",
    title: "Periodicals",
  },
  {
    level: "7",
    category: "3",
    room: "Stcks",
    spaces: "7.02",
    title: "Davis Classroom",
  },
  {
    level: "7",
    category: "3",
    room: "SCP",
    spaces: "7.03",
    title: "Stacey Sheriff",
  },
  {
    level: "7",
    category: "3",
    room: "SC",
    spaces: "7.04",
    title: "Carol Hurney",
  },
  {
    level: "7",
    category: "3",
    room: "134",
    spaces: "7.05",
    title: "Jason Parkhill",
  },
];

export default AsideData;
